version: '3.9'
services:
  web:
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - redis
  peer1:
    build: .
    environment:
      - START_AS_PEER=true
      - PEER_PORT=3001
    ports:
      - '3001:3001'
    depends_on:
      - web
  peer2:
    build: .
    environment:
      - START_AS_PEER=true
      - PEER_PORT=3002
    ports:
      - '3002:3002'
    depends_on:
      - web
  redis:
    image: 'redis:alpine'
